version: "3.8"
services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: "monitor-web"
    ports:
      - "5432:5432"
