export const BodyDefault = {
  SacadoCPFCNPJ: '08357906000170',
  SacadoEnderecoNumero: '987',
  SacadoEnderecoBairro: 'Centro',
  SacadoEnderecoCEP: '87045430',
  SacadoEnderecoCidade: 'Maringá',
  SacadoEnderecoComplemento: 'Fundos',
  SacadoEnderecoLogradouro: 'Rua teste, 987',
  SacadoEnderecoPais: 'Brasil',
  SacadoEnderecoUF: 'PR',
  SacadoNome: 'FooBarTeste',
  SacadoTelefone: '4499999999',
  SacadoCelular: true,

  TituloDataEmissao: '22/04/2019',
  TituloDataVencimento: '24/04/2019',
  TituloMensagem01: 'Teste',
  TituloMensagem02: 'Nao receber apos 30 dias de atraso',
  TituloMensagem03: 'Sujito a protesto apos 30 dias',
  TituloNumeroDocumento: '321',
  TituloDocEspecie: '01',
  TituloNossoNumero: 123456,
  TituloValor: '0,10',
  titulosacadoravalistaenderecoNumero: '155',
  TituloLocalPagamento: 'Pagável em qualquer banco até o vencimento.',
  TituloSacadorAvalistaBairro: 'JDestes',
};
